title: Default Page

columns:
  main:
    sections:
      pages:
        width: 1/3
        type: pages
        template: default
      files:
        type: files
      fields:
        type: fields
        fields:
          headlings:
            type: blocks
            fieldsets:
              - heading
              - text
              - video
